# Generated by Django 3.0.6 on 2020-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='stu_profile',
            field=models.FileField(blank=True, default='ghgg', null=True, upload_to='images/'),
        ),
    ]
