# Generated by Django 3.0.6 on 2020-06-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0002_auto_20200621_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=30)),
                ('emp_id', models.IntegerField(default='')),
                ('emp_joiningdate', models.DateField(blank=True, default='', null=True)),
                ('emp_type', models.CharField(blank=True, choices=[('t', 'Teaching staff'), ('n', 'Non teaching staff')], default='', max_length=20, null=True)),
                ('emp_profile', models.FileField(blank=True, default='hhh', null=True, upload_to='images/')),
                ('emp_mobileno', models.IntegerField(default='')),
                ('emp_salary', models.IntegerField(default='')),
                ('emp_fathersname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('emp_experience_or_specilalization', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('emp_gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], default='', max_length=20, null=True)),
                ('emp_CNIC', models.CharField(default='', max_length=30)),
                ('emp_email', models.CharField(default='', max_length=100)),
                ('emp_rligion', models.CharField(blank=True, choices=[('h', 'hindu'), ('m', 'muslim'), ('s', 'sikh'), ('g', 'gujrati'), ('c', 'cristian'), ('o', 'other')], default='', max_length=20, null=True)),
                ('emp_education', models.CharField(default='', max_length=100)),
                ('emp_dob', models.DateField(blank=True, default='', null=True)),
                ('emp_bloodgroup', models.CharField(blank=True, choices=[('o', 'o+'), ('a+', 'A+'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o-', 'O-'), ('a-', 'A-')], default='', max_length=20, null=True)),
                ('emp_address', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
