# Generated by Django 3.0.6 on 2020-07-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0003_employeeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, default='', null=True)),
                ('to_date', models.DateField(blank=True, default='', null=True)),
                ('income_des', models.CharField(default='', max_length=30)),
                ('income_ammount', models.IntegerField(default='')),
                ('expense_des', models.CharField(default='', max_length=30)),
                ('expense_ammount', models.IntegerField(default='')),
                ('net_balance', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Expenseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, default='', null=True)),
                ('expense_des', models.CharField(default='', max_length=30)),
                ('expense_ammount', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Incomeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, default='', null=True)),
                ('income_des', models.CharField(default='', max_length=30)),
                ('income_ammount', models.IntegerField(default='')),
            ],
        ),
    ]
