# Generated by Django 3.0.6 on 2020-07-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comapp', '0005_auto_20200705_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='from_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='expense_des',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='income_des',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='net_balance',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='to_date',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
